packages:
  - "packages/*"
  - "packages/adapters/*"
allowBuilds:
  esbuild: true
  workerd: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.3.2
  vitest: 5.0.1
  vite-plus: 0.3.2
overrides:
  vite@*: "catalog:"
  vitest@*: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
minimumReleaseAgeExclude:
  - "@torpor/build"
  - "@torpor/ui"
  - "@torpor/unplugin"
  - "@torpor/view"
  - "@torpor/adapter-cloudflare"
  - "@torpor/adapter-node"
